### ISSUE TITLE
Provide a way to use local Iglu schemas

### ISSUE THREAD

**Issue by benjben** [snowplow-incubator/snowplow-micro#49] opened 2021-06-03 13:11 UTC
Currently if we want to use custom schemas in Micro, we need to run an HTTP server or Iglu server beside it.

We want to be able to specify a path holding schemas and use them directly.

**Comment by paulboocock** [comment] 2022-03-16 14:03
Duplicate of #8 and now released.

**Closed by paulboocock** 2022-03-16 14:03 UTC
Labels: enhancement
